Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> a=int(input('Enter the first number:'))
... 
... b=int(input('Enter the second number:'))
... 
... c=int(input('Enter the third number:'))
... 
... largest=0
... 
... if a>b and a>c:
...     largest=a
... 
... elif b>c:
...     largest=b
... 
... else:
...     largest=c
... 
